# Generated by Django 5.2.11 on 2026-02-23 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('accession', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('family', models.TextField(null=True)),
                ('genus', models.TextField(null=True)),
                ('species', models.TextField(null=True)),
                ('organism_name', models.TextField(null=True)),
                ('molecular_type', models.TextField(null=True)),
                ('collection_date', models.TextField(null=True)),
                ('country', models.TextField(null=True)),
                ('completenessFlag', models.TextField(null=True)),
                ('source', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('accession', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='genomes.sequence')),
                ('length', models.IntegerField(null=True)),
                ('gc', models.FloatField(null=True)),
                ('entropy', models.FloatField(null=True)),
                ('melting_t', models.FloatField(null=True)),
            ],
        ),
    ]
