# Generated by Django 5.2.11 on 2026-02-25 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceMetrics',
            fields=[
                ('sequence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metrics', serialize=False, to='genomes.sequence')),
                ('length', models.IntegerField(blank=True, null=True)),
                ('gc_content', models.FloatField(blank=True, null=True)),
                ('entropy', models.FloatField(blank=True, null=True)),
                ('melting_temp', models.FloatField(blank=True, null=True)),
                ('pct_a', models.FloatField(blank=True, null=True)),
                ('pct_c', models.FloatField(blank=True, null=True)),
                ('pct_g', models.FloatField(blank=True, null=True)),
                ('pct_t', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(blank=True, max_length=100, null=True)),
                ('genus', models.CharField(blank=True, max_length=100, null=True)),
                ('species', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='completenessFlag',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='family',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='molecular_type',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='source',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='species',
        ),
        migrations.AddField(
            model_name='sequence',
            name='source_db',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='organism_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='taxonomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='genomes.taxonomy'),
        ),
        migrations.DeleteModel(
            name='Metrics',
        ),
    ]
