# Generated by Django 5.2.11 on 2026-02-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0002_sequencemetrics_taxonomy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='first_collection',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='last_collection',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='max_gc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='max_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='min_gc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='min_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='sequence_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='sequence',
            index=models.Index(fields=['collection_date'], name='genomes_seq_collect_97f8b7_idx'),
        ),
        migrations.AddIndex(
            model_name='sequence',
            index=models.Index(fields=['country'], name='genomes_seq_country_30b105_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomy',
            index=models.Index(fields=['-sequence_count', 'species'], name='genomes_tax_sequenc_48e22e_idx'),
        ),
    ]
