# Generated by Django 5.2.11 on 2026-02-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0003_taxonomy_first_collection_taxonomy_last_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='max_ent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='max_mt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='min_ent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='min_mt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
