# Generated by Django 6.0.2 on 2026-03-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0004_taxonomy_max_ent_taxonomy_max_mt_taxonomy_min_ent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='genome_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
