# Generated by Django 6.0.2 on 2026-03-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0005_sequence_genome_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='completeness_flag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='molecular_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='genome_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
