# Generated by Django 6.0.2 on 2026-06-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0006_sequence_completeness_flag_sequence_molecular_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('database_usage', 'Database usage'), ('sequence_analysis', 'Sequence analysis'), ('data_download', 'Data download'), ('genomic_metrics', 'Genomic metrics'), ('api_access', 'API access'), ('technical_issue', 'Technical issue'), ('scientific_question', 'Scientific question'), ('other', 'Other')], max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In review'), ('answered', 'Answered'), ('closed', 'Closed')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='genomes_con_status_b6a703_idx')],
            },
        ),
    ]
